public class TemplateQuoteCalculator implements SBQQ.QuoteCalculatorPlugin, SBQQ.QuoteCalculatorPlugin2 {

    public Set<String> getReferencedFields() {
        Set<String> fields = new Set<String>();
        return fields;
    }

    public void onInit(List<SObject> lines) {

    }

    public void onBeforePriceRules(SObject quote, List<SObject> lines) {

    }

    public void onAfterPriceRules(SObject quote, List<SObject> lines) {

    }

    public void onBeforeCalculate(SObject quote, List<SObject> lines) {

    }

    public void onAfterCalculate(SObject quote, List<SObject> lines) {

    }
}